name: Run Ultimate Master Algo

on:
  schedule:
    - cron: '*/5 * * * *'  # runs every 5 minutes
  workflow_dispatch:  # allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install requests pandas yfinance ta pyotp SmartApi

      - name: Run Bot
        run: python your_bot_script.py
