name: Ultimate Master Algo Bot

on:
  schedule:
    # Run Monday to Friday at 9:10 AM IST (3:40 UTC)
    - cron: '40 3 * * 1-5'
  workflow_dispatch:  # Manual trigger

jobs:
  run-algo:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # Max 8 hours

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ta yfinance requests pyotp pandas SmartApi logzero websocket-client smartapi-python datetime pycryptodome multitasking peewee

    - name: Run Ultimate Master Algo (9:10 → 15:30 IST)
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        echo "🚀 Starting Ultimate Master Algo at $(date)"
        python ultimate_algo.py &
        PID=$!
        # Calculate seconds until 15:30 IST
        END_TIME=$(date -d "15:30 IST today" +%s)
        NOW=$(date +%s)
        SLEEP_SEC=$((END_TIME - NOW))
        if [ $SLEEP_SEC -gt 0 ]; then
          sleep $SLEEP_SEC
        fi
        echo "🛑 Stopping Ultimate Master Algo at 15:30 IST"
        kill $PID || true

    - name: Notify workflow completed
      run: echo "✅ Ultimate Master Algo workflow finished at $(date)"
