name: Test Algo (2:25-2:27 AM IST)

on:
  schedule:
    # Run at 2:25 AM IST (8:55 PM UTC previous day)
    - cron: '55 20 * * *'
  workflow_dispatch:  # Manual trigger

jobs:
  test-algo:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 5 minutes max

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ta yfinance requests pyotp pandas SmartApi logzero websocket-client smartapi-python datetime pycryptodome multitasking peewee

    - name: Run Test (2:25 AM - 2:27 AM IST)
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        echo "🧪 STARTING TEST at $(TZ='Asia/Kolkata' date)"
        echo "🕒 Current IST: $(TZ='Asia/Kolkata' date '+%H:%M:%S')"
        
        # Run for exactly 2 minutes (2:25 - 2:27 AM IST)
        end_time=$(date -d "2 minutes" +%s)
        
        while [ $(date +%s) -lt $end_time ]; do
          CURRENT_TIME_IST=$(TZ='Asia/Kolkata' date '+%H:%M:%S')
          echo "⏰ Running at: $CURRENT_TIME_IST IST"
          
          # Run one iteration
          python ultimate_algo.py
          
          # Wait 10 seconds
          sleep 10
        done
        
        echo "✅ TEST COMPLETED at $(TZ='Asia/Kolkata' date '+%H:%M:%S')"
        echo "🛑 Stopped at 2:27 AM IST as scheduled"

    - name: Notify test completion
      run: |
        echo "🎯 Test completed at $(TZ='Asia/Kolkata' date)"
