name: 8:58–9:00 PM IST Test Run

on:
  schedule:
    # Runs once daily at 8:58 PM IST (15:28 UTC)
    - cron: "28 15 * * *"
  workflow_dispatch:  # optional manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot for exactly 2 minutes (8:58–9:00 PM IST)
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "🚀 Starting bot at $(TZ='Asia/Kolkata' date)"
          echo "⏰ Target stop time: 9:00 PM IST"
          end_time=$(( $(date +%s) + 120 ))  # 120 seconds = 2 minutes
          while [ $(date +%s) -lt $end_time ]; do
            CURRENT_TIME=$(TZ='Asia/Kolkata' date '+%H:%M:%S')
            echo "🔄 Running iteration at $CURRENT_TIME IST"
            python main.py
            sleep 30
          done
          echo "✅ Bot stopped at $(TZ='Asia/Kolkata' date)"
