name: Ultimate Master Algo Bot

on:
  schedule:
    # Run Monday to Friday at 9:10 AM IST (3:40 UTC) and ensure it runs till 3:30 PM IST
    - cron: '40 3 * * 1-5'
  workflow_dispatch:  # Manual trigger

jobs:
  run-algo:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # Max 8 hours (9:10 AM to 5:10 PM)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ta yfinance requests pyotp pandas SmartApi logzero websocket-client smartapi-python datetime pycryptodome multitasking peewee

    - name: Set timezone to IST and run algo
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        echo "🚀 Starting Ultimate Master Algo at $(TZ='Asia/Kolkata' date)"
        echo "🕘 Current IST time: $(TZ='Asia/Kolkata' date '+%H:%M:%S')"
        
        # Run the algorithm continuously until 3:30 PM IST
        while true; do
          CURRENT_TIME_IST=$(TZ='Asia/Kolkata' date '+%H:%M')
          echo "🕒 Checking time: $CURRENT_TIME_IST IST"
          
          # Stop at 3:30 PM IST
          if [[ "$CURRENT_TIME_IST" > "15:30" ]]; then
            echo "🛑 Market closed at 3:30 PM IST - Stopping algorithm"
            send_telegram "🛑 Market closed at 3:30 PM IST - Algorithm stopped automatically"
            break
          fi
          
          # Run one iteration of the algorithm
          python ultimate_algo.py
          
          # Wait 30 seconds before next iteration
          sleep 30
        done
        
        echo "✅ Ultimate Master Algo completed at $(TZ='Asia/Kolkata' date)"

    - name: Notify workflow completion
      run: |
        echo "✅ Ultimate Master Algo workflow finished at $(TZ='Asia/Kolkata' date)"
